@xtreme-will-tran using jdk.nashorn.internal.objects.Global.allocate to create an array, there are inconsistencies in other methods between Java runtime versions that cause NoSuchMethodErrors